sonar.projectKey=ecomera-product-service
sonar.projectName=ecomera-product-service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.jacoco.reportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
