name: Product Service CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  call-ci:
    uses: ecomera-ecosystem/.github/.github/workflows/ci.yml@main
    with:
      java_version: '17'
      maven_goals: 'clean verify'
      service-name: 'product-service'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
