name: Product Service Docker

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  call-docker:
    permissions:
      contents: read
      packages: read
    uses: ecomera-ecosystem/.github/.github/workflows/docker.yml@main
    with:
      image_name: "ammysf/ecomera-product-service"
      dockerfile: "./Dockerfile"
      context: "."
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}